service: pintweet

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-2

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 4000

functions:
  graphql:
    handler: gateway.graphqlHandler
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true